# In the name of God


# Introduction to Python, Numpy and Matplotlib assignment
## Ferdowsi University of Mashhad
## Neural Networks and Deep Learning course 
## Professor: Dr. Sayed Kamaledin Ghiasi-shirazi
## Authors and Teaching assistants: Kamyar Nasiri - Emad Aghajanzadeh

# Introduction to Numpy

In [1]:
import numpy as np

##  Array Creation


### np.array()

Create an array using lists and tuples of Python and "array" function of numpy. 

As your first code, please create a 1 dimention array with elements : A = {1, 2, 3}.... Use np.array()

In [2]:
# write your code here
elements = np.array([1, 2, 3]) 
print(elements)
# write your code here

[1 2 3]


Now let's see what is the dimension of array A .... Use "ndim" attribute 

In [3]:
# write your code here
print(elements.ndim)
# write your code here

1


Do you want to create an array with more dimensions? Let's see the matrices. Use np.array() to create array B. the first row of B has elements {1 , 2} and the second row has {3 , 4}

In [4]:
# write your code here
arrayB = np.array([[1,2],[3,4]])
print(arrayB)
# write your code here

[[1 2]
 [3 4]]


Find the dimension:

In [5]:
# write your code here
print(arrayB.ndim)
# write your code here

2


We are going to create a matrix whose all elements are zero. Use np.zeros. Set the dimension to (3,4)

In [6]:
# write your code here
print(np.zeros((3,4)))
# write your code here

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


After that, we are going to create a matrix whose all elements are one. Use np.ones. Set the dimension to (3,4)

In [7]:
# write your code here
print(np.ones((3,4)))
# write your code here

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


and in the next step, we are going to create an identity matrix. Use np.eye. Set the dimension to 4. It will create a 4*4 matrix

In [8]:
# write your code here
print(np.eye(4))
# write your code here

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### np.arange()  --- np.linspace()

Let's work with two useful functions. 1- np.arange()  - 2- np.linspace()

For the first one, np.arange() creates sequence of numbers. This is the exact form of this function : np.arange(start, stop, step).... Start is start of interval. Stop is end of interval and Step is spacing between values. It returns a ndarray.


Pay attention! You have to mention "stop" argument whereas you can use default values for "start" and "step". The default value of start is 0 and default value of step is 1.

Create an array whose elements start in 0, end in 4 and they increase one by one. So you will have {0, 1, 2, 3, 4} ... Use np.arange() and just use "stop" argument!!! Be careful... set "stop" argument to real stop number plus 1 ! 

In [9]:
# write your code here
print(np.arange(4+1))
# write your code here

[0 1 2 3 4]


Let's change it to have an array with elements like this: { 10.0 , 10.2 , 10.4 , 10.6 , 10.8 }

In [10]:
# write your code here
print(np.arange(10.0,11.0,0.20))
# write your code here

[10.  10.2 10.4 10.6 10.8]


Another useful function to create arrays in numpy is np.linspace() . The exact form of this function is : np.linspace(start , stop , num). It returns an array with sequence of numbers. "Start" is the starting value of the sequence. "Stop" is the end value of the sequence and "num" is number of samples to generate.


Pay attention! You have to mention "start" and "stop" argument whereas ou can use default value for "num" that is 50. There is another important argument called "endpoint" that if it is True, "stop" is the last sample. Otherwise, it is not included. Default is True.

Let's see an example. Generate an array whose elements are between 0 and 10. we want to have 5 numbers in this array.

In [11]:
# write your code here

print(np.linspace(0,10,5))
# write your code here

[ 0.   2.5  5.   7.5 10. ]


Let's see an useful example. We want to know the sine values from 0 to 2π but just multiples of π/2 . You can use both np.arange() and np.linspace(). But we ask you to use np.linspace(). Then use np.sin(). You should know that a mathematical function like sin whose argument is a array, will operate on whole elements of array. We will learn it later.

First create an array using np.linspace() according to above description and call it C. Then use np.sin() on array C.


In [12]:
from numpy import pi

# write your code here

arr = np.linspace(0,pi*2,4,endpoint=False)

print(np.sin(arr))

# write your code here

[ 0.0000000e+00  1.0000000e+00  1.2246468e-16 -1.0000000e+00]


Now we want to compare np.arange() and np.linspace() with an example. We defined the N variable in this cell. Use this variable as "step" argument in np.arange() and "num" variable in np.linspace(). In both functions set "start" to 0 and "stop" to 40. 

In [13]:
N = 5
# write your code here

print(np.linspace(0,40,N))
print(np.arange(0,40,N))

# write your code here

[ 0. 10. 20. 30. 40.]
[ 0  5 10 15 20 25 30 35]


### Create random arrays

Sometimes we want to generate arrays with random values. It will be possible using np.random.rand() .  

np.random.rand(d1,d2,...,dn) returns a ndarray with random values in the given shape. Let's do an exercise. Generate an array with shape(5, 4) randomly.

In [14]:
# write your code here

print(np.random.rand(4,5))

# write your code here

[[0.37755549 0.01977114 0.85853245 0.61451312 0.98951064]
 [0.09470725 0.98382219 0.35812322 0.45246545 0.58994455]
 [0.77199008 0.12935952 0.25936119 0.94646711 0.28895492]
 [0.40757876 0.17688559 0.59429529 0.45523468 0.9043669 ]]


If you want to have integer random numbers, Use np.random.randint(low, high, size). Returns random integers from "low" (inclusive) to "high" (exclusive). "size" is the size of array. At first create a vector with random integer elements whose elements are between 0 and 10 and the size is 5. Then create an array with random integer elements whose elements are between 0 and 10 and the size of this array is (2,3). Pay attention! using "low" argument is not necessary so it will set to zero.

In [15]:
# write your code here

print(np.random.randint(10,size=(2,3)))

# write your code here

[[6 9 2]
 [3 4 2]]


Let's see an important creation array function. np.random.randn() .... It's just like np.random.rand() function which Generates elements from the “standard normal” distribution. Numbers in this distribution have mean 0 and variance 1. Please create an array using np.random.randn() with size (3,4,1) with mean=4 and variance=10.

In [16]:
# write your code here
#sigma * np.random.randn(d0, d1, ..., dn) + mu
#when mu is the mean and sigma is the variance
print(10*np.random.randn(3,4,1)+4)
# write your code here

[[[-0.15050348]
  [ 7.00788862]
  [27.15940449]
  [ 6.99554794]]

 [[ 7.09571689]
  [-8.5529711 ]
  [ 2.46317907]
  [ 0.18362311]]

 [[16.3179983 ]
  [15.17977349]
  [14.01777782]
  [15.16388486]]]


## Shape of numpy arrays

As you can see in the last exercise, we have generated a 3d array. So what should we do if we want to know the shape and dimension of an array?

Use shape attribute of numpy array. Generate an integer randomly array with size (4,3,3) and call it D. Tell us its shape and then print the dimension of this array .... Also please print "size" attribute. What's their differences?

In [17]:
# write your code here

D=np.random.randint(10, size=(4,3,3))
print(D)
print(D.shape)
print(D.ndim)
print(np.size(D))


# write your code here

[[[4 1 5]
  [8 5 2]
  [9 1 9]]

 [[9 1 9]
  [5 1 4]
  [5 9 4]]

 [[7 1 3]
  [3 8 7]
  [7 9 3]]

 [[3 9 7]
  [1 2 7]
  [2 5 6]]]
(4, 3, 3)
3
36


It was obvious. Let's do some changes on array D. Use "reshape" attribute on array D. set its shape to (4,3). Is it possible? If it is not, so calculate the proper shape and reshape it to 2d array. "size" attribute is useful to calculate.

In [18]:
# write your code here

D.reshape((4,9))

# write your code here

array([[4, 1, 5, 8, 5, 2, 9, 1, 9],
       [9, 1, 9, 5, 1, 4, 5, 9, 4],
       [7, 1, 3, 3, 8, 7, 7, 9, 3],
       [3, 9, 7, 1, 2, 7, 2, 5, 6]])

If the calculation is not easy, don't worry! Numpy will help you. Just set the second dimension to -1. the second dimention will be calculated. Let's see on array D:

In [19]:
# write your code here
D.reshape((4,-1))
# write your code here

array([[4, 1, 5, 8, 5, 2, 9, 1, 9],
       [9, 1, 9, 5, 1, 4, 5, 9, 4],
       [7, 1, 3, 3, 8, 7, 7, 9, 3],
       [3, 9, 7, 1, 2, 7, 2, 5, 6]])

Before going to another example, set the first dimension of array D to 9. It is also a useful change.

In [20]:
# write your code here

D.reshape((9,-1))
# write your code here

array([[4, 1, 5, 8],
       [5, 2, 9, 1],
       [9, 9, 1, 9],
       [5, 1, 4, 5],
       [9, 4, 7, 1],
       [3, 3, 8, 7],
       [7, 9, 3, 3],
       [9, 7, 1, 2],
       [7, 2, 5, 6]])

Let's see array.resize() for ndarrays. What is the difference between "reshape" attribute and np.resize()? "reshape" won't change the original array however array.resize() returns a new array with the specified shape and changes the original array shape. Exact form of this function: array.resize(new_shape). Change the array D size to (4,9). Then print array D.

In [21]:
# write your code here

D.resize((4,9))
print(D)
# write your code here

[[4 1 5 8 5 2 9 1 9]
 [9 1 9 5 1 4 5 9 4]
 [7 1 3 3 8 7 7 9 3]
 [3 9 7 1 2 7 2 5 6]]


Now we want to do something amazing. We want to add new dimensions to an array. It will be possible using np.newaxis

A good example is here. Search how to add dimension with np.newaxis to array E.

In [22]:
E = np.random.rand(2,3)
print(E)
print(E.shape)
# write your code here
E=E[np.newaxis]
# write your code here
print(E)
print(E.shape)

[[0.05431203 0.72827308 0.45531036]
 [0.686095   0.74623983 0.97765457]]
(2, 3)
[[[0.05431203 0.72827308 0.45531036]
  [0.686095   0.74623983 0.97765457]]]
(1, 2, 3)


As you know 1d arrays and 2d arrays are completely different. But you may consider 1d array with 4 elements as 2d array with shape (4,1). They are not equal in Python. Let's see how they are different. Create an array of consecutive numbers using np.arange() with "stop" in 10. print the shape and ndim of this ndarray. 

In [43]:
# write your code here

A = np.arange(10)

print(A.ndim)
print(A.shape)


# write your code here

1
(10,)


So you can see it was a vector or 1d array. How can we change it to 2d array? Do it and print the shape and ndim of this ndarray.  

In [45]:
# write your code here

R =A.reshape(2,-1)
print(R.shape)
print(R.ndim)

# write your code here 

(2, 5)
2


## Operations

It's easy to do basic operations such as adding or subtracting using numpy. If you have n dimensional matrix, it doesn't matter.

Use random array generation to create a 3*4 matrix. Print it. Then use an array whose all elements are 1 with the same size. add it to the random array. See the result.

In [38]:
# write your code here

array =np.random.rand(3,4)
print(array)

ones =np.ones((3,4))
print(ones)

print(array + ones)

# write your code here

[[0.70771476 0.61365962 0.15177458 0.8608198 ]
 [0.44105959 0.96516419 0.21646115 0.06968827]
 [0.99979466 0.17310251 0.4391698  0.78156105]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1.70771476 1.61365962 1.15177458 1.8608198 ]
 [1.44105959 1.96516419 1.21646115 1.06968827]
 [1.99979466 1.17310251 1.4391698  1.78156105]]


As you can see, dimensions of these operand matrices must be the same. But there is an important exception that calls Broadcasting.

Broadcasting describes how numpy treats arrays with different shapes during arithmetic operations. Actually the smaller array is “broadcast” across the larger array so that they have compatible shapes. The simplest broadcasting example occurs when an array and a scalar value are combined in an operation. You can see other examples here: https://numpy.org/doc/stable/user/basics.broadcasting.html 

In this example, array J and scalar value "b" are defined. Just do multiplication on them.

In [26]:
a1 = np.ones((3,1))
b1 = np.random.rand(3,1)
J = a1 + b1
print(J)
b = 6
# write your code here
print(J*b)
# write your code here

[[1.75060189]
 [1.12649026]
 [1.30175588]]
[[10.50361132]
 [ 6.75894159]
 [ 7.81053531]]


To multiply matrices elementwise, use * symbol. So the operand matrices must have the same shape. Then print the shape of result.

In [27]:
K = np.random.randint(1, 20, size=(3,5))
L = np.random.randint(1, 20, size=(3,5))
# write your code here
M = K * L
print(M.shape)


# write your code here

(3, 5)


To multiply matrices use @ symbol or array1.dot(array2) function. Multiply matrix M and N. Then print the shape of result.

In [28]:
M = np.random.randint(1, 20, size=(3,5))
N = np.random.randint(1, 20, size=(5,10))
# write your code here
P=M@N
print(P.shape)
# write your code here

(3, 10)


Another useful operation is transposing matrices. Do it for matrix O.

In [29]:
O = np.arange(20).reshape(4,5)
print(O)
# write your code here
T=O.transpose()
print(T)
# write your code here

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]


Now we're going to use array.sum() , array.min() and array.max(). array.sum() returns the sum of all elements in the array. array.min() returns the minimum element and array.max() returns the maximum element of array. Try to use them.

In [30]:
P = np.random.rand(2,3)
print(P)
# write your code here
print(P.sum())
print(P.min())
print(P.max())


# write your code here

[[0.0690787  0.53188834 0.46293693]
 [0.70695649 0.61398125 0.67095065]]
3.0557923607019633
0.06907869648967824
0.7069564905270004


By default, functions that mentioned above apply to the array as though it were a list of numbers, regardless of its shape. However, by specifying the axis parameter you can apply an operation along the specified axis of an array.

For the array Q, calculate the maximum value of each column and minimum of each row. 

In [31]:
Q = np.random.rand(3,4)
print(Q)
# write your code here

print(Q.max(1))

print(Q.transpose().min(1))

# write your code here

[[0.57333019 0.01221332 0.57640575 0.6899861 ]
 [0.1747666  0.05306778 0.70930899 0.89503015]
 [0.54860759 0.68126    0.13263853 0.13191391]]
[0.6899861  0.89503015 0.68126   ]
[0.1747666  0.01221332 0.13263853 0.13191391]


Now calculate the sum of elements in third dimension for array R. Check its shape attribute.

In [52]:
R = np.random.randn(3,4,2) * 10 + 5
print(R)
# write your code here

print(R[2,:,:].sum())

# write your code here

[[[-11.26816326  16.0811637 ]
  [  3.47323601  12.43297055]
  [ -2.32356577   6.90230504]
  [ 11.97511794   7.50473492]]

 [[ 14.83134726   4.76197405]
  [ 12.61178073  16.92759385]
  [  5.19883641   5.41882945]
  [ 14.3486931   17.8557626 ]]

 [[ -7.34953166  11.02221372]
  [  2.49355248  24.17995367]
  [ -0.47364851  14.29259855]
  [  1.80755847  13.79754185]]]
59.770238563395964


## Index and iteration

### 1d array

We just want to use indexes to make changes on 1d arrays

Create an array with 9 elements between 10 and 50. Return first 3 elements with indexing and then set the value of odd indexes to 0.

In [33]:
# write your code here

S= np.linspace(10,50,9)[0:3]
for i in np.arange(len(S)):
    if i%2 != 0:
        S[1]=0

# write your code here
print(S)

[10.  0. 20.]


Use indexes to reverse array S

In [39]:
# write your code here
print(S[:None:-1])
# write your code here

[20.  0. 10.]


Let's see an advanced example. Consider array T.  set the value of indexes [1,2,5,7] to [3,8,5,10] . 

In [40]:
T = np.linspace(10, 90, 9)
print(T)
# write your code here
T[1]=3
T[2]=8
T[5]=5
T[7]=10

print(T)

# write your code here

[10. 20. 30. 40. 50. 60. 70. 80. 90.]
[10.  3.  8. 40. 50.  5. 70. 10. 90.]


### nd array

According to array U, print the element exists in row 3 and column 5. Then print the elements are in row 2. Then print the elements are in columns 2, 3 and 4. 

In [36]:
U = np.random.randint(50, size=(6,7))
print(U)
# write your code here
print(U[3,5])
print(U[2:3,:])
print(U[:,2:5])


# write your code here

[[20 21  4  5 26  7 19]
 [16 35  4  8 28  1 18]
 [ 8 35 44 44 11 29 45]
 [43 36 10 44 35 17 20]
 [20  5  5 37 12  1  6]
 [24 32 24 18 21 22 16]]
17
[[ 8 35 44 44 11 29 45]]
[[ 4  5 26]
 [ 4  8 28]
 [44 44 11]
 [10 44 35]
 [ 5 37 12]
 [24 18 21]]


### Indexing with boolean arrays

Consider the array V that we've defined. Array b just selects the elements whose values are greater than 4. Print the array b to see what's its type. Then give the array b as the index for array V. You will see the result is just the elements their insex was True in array b. After that set these elements to -1.

In [54]:
V = np.arange(15).reshape(3,5)
print(V)
b = V > 4 
# write your code here
print(b)
print(b*V)


# write your code here

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[False False False False False]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
[[ 0  0  0  0  0]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


Now you are ready to use Numpy. But actually there are lots of functions and attributes that we didn't mention and you should find and use them according to your needs.

---

## **Best wishes**